import Menu from "../componentes/menu"

export const metadata = {
  title: 'Atividade 2.02',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Menu/>
      {children}
      </body>
    </html>
  )
}
